
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Gradle Plugins
loom_version=1.9-SNAPSHOT
arch_plugin_version=3.4-SNAPSHOT
shadow_version=8.1.1

quiltflower_version=1.10.0

grgit_version=5.0.0
cursegradle_version=1.4.0
modrinth_version=2.3.1
github_api_version=1.307

# Mod Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
enabled_platforms=fabric,neoforge

# Project Properties
archives_base_name=builtin-servers
mod_version=2.2+1.21
maven_group=io.github.lucaargolo

architectury_version=13.0.8

# Fabric Properties
fabric_loader_version=0.16.9
fabric_api_version=0.107.0+1.21.1

# NeoForge Properties
neoforge_version=21.1.80

# Forge Properties (deprecated, kept for reference)
forge_version=1.20.1-47.1.44

#Publishing
curseforge_id=473131
modrinth_id=IupkwRPf


